import type { Metadata } from "next"
import "./globals.css"
import SideBar from "@/components/SideBar"
import { Box } from "@mui/material"
import NavBar from "@/components/NavBar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="flex">
        <SideBar />
        <Box sx={{ display: "flex", flexDirection: "column", width: "100%" }}>
          <NavBar />
          {children}
        </Box>
      </body>
    </html>
  )
}
